const SUBI_CONNECT_PUBLIC_BASE_URL = process.env
  .SUBI_CONNECT_PUBLIC_BASE_URL as string;
if (!SUBI_CONNECT_PUBLIC_BASE_URL) {
  throw new Error('SUBI_CONNECT_PUBLIC_BASE_URL is not set');
}

const SUBI_CONNECT_SANDBOX_PUBLIC_BASE_URL = process.env
  .SUBI_CONNECT_SANDBOX_PUBLIC_BASE_URL as string;
if (!SUBI_CONNECT_SANDBOX_PUBLIC_BASE_URL) {
  throw new Error('SUBI_CONNECT_SANDBOX_PUBLIC_BASE_URL is not set');
}

const SUBI_CONNECT_IMAGES_BASE_URL = process.env
  .SUBI_CONNECT_IMAGES_BASE_URL as string;
if (!SUBI_CONNECT_IMAGES_BASE_URL) {
  throw new Error('SUBI_CONNECT_IMAGES_BASE_URL is not set');
}

export {
  SUBI_CONNECT_PUBLIC_BASE_URL,
  SUBI_CONNECT_SANDBOX_PUBLIC_BASE_URL,
  SUBI_CONNECT_IMAGES_BASE_URL,
};
