name: Snapshot Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the snapshot release'
        required: true
        default: 'snapshot'

jobs:
  snapshot:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org
          scope: '@subifinancial'

      - name: 🧩 Install Dependencies
        run: npm ci

      - name: 🏗️ Build
        run: npm run build:prod
        env:
          SUBI_CONNECT_IMAGES_BASE_URL:
            ${{ secrets.SUBI_CONNECT_IMAGES_BASE_URL }}
          SUBI_CONNECT_PUBLIC_BASE_URL:
            ${{ secrets.SUBI_CONNECT_PUBLIC_BASE_URL }}
          SUBI_CONNECT_SANDBOX_PUBLIC_BASE_URL:
            ${{ secrets.SUBI_CONNECT_SANDBOX_PUBLIC_BASE_URL }}

      - name: 🖼️ Create and publish snapshot
        run: |
          npx changeset version --snapshot ${{ github.event.inputs.tag }}
          npx changeset publish --tag ${{ github.event.inputs.tag }} --no-git-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
